import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-black text-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold mb-2">Terms of Use</h1>
        <p className="text-sm text-zinc-500 mb-10">Last updated: February 27, 2026</p>

        <div className="space-y-8 text-zinc-300 text-sm sm:text-base leading-relaxed">
          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Careera website at careera.co (the "Service"), you
              agree to be bound by these Terms of Use ("Terms"). If you do not agree to these
              Terms, you may not use the Service. We reserve the right to modify these Terms
              at any time, and your continued use constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Careera provides an AI-powered leadership assessment and coaching platform. The
              Service includes a leadership readiness questionnaire, personalized report
              generation, and optional coaching call booking. Reports are generated using
              artificial intelligence and are intended as guidance tools, not professional
              certifications or guarantees of career outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">3. Eligibility</h2>
            <p>
              You must be at least 18 years old to use this Service. By using the Service,
              you represent and warrant that you meet this age requirement and have the legal
              capacity to enter into these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">4. User Conduct</h2>
            <p className="mb-3">When using the Service, you agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide false or misleading information in the assessment.</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble any part of the Service.</li>
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Interfere with or disrupt the Service or its infrastructure.</li>
              <li>Attempt to gain unauthorized access to any systems or networks connected to the Service.</li>
              <li>Use automated tools, bots, or scripts to access the Service without our prior written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">5. Intellectual Property</h2>
            <p>
              All content, features, and functionality of the Service — including but not
              limited to text, graphics, logos, design, software, and the AI-generated reports —
              are the exclusive property of Careera or its licensors and are protected by
              copyright, trademark, and other intellectual property laws. You may download
              and use your personalized report for personal, non-commercial purposes only.
              You may not reproduce, distribute, or create derivative works from any part
              of the Service without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">6. AI-Generated Content</h2>
            <p>
              Reports and analyses generated by our Service use artificial intelligence,
              including OpenAI's language models. While we strive for accuracy and relevance,
              AI-generated content may contain errors, inaccuracies, or generalizations.
              The reports are provided "as is" and should not be considered professional
              coaching advice, career counseling, or a substitute for professional guidance.
              You acknowledge that results may vary and that Careera does not guarantee
              specific career outcomes based on the report's recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">7. Payments & Refunds</h2>
            <p>
              Certain features of the Service may require payment. All prices are displayed
              at the time of purchase. Payments are processed securely through our payment
              provider. Due to the digital nature of the reports, all sales are final.
              Refund requests may be considered on a case-by-case basis by contacting us at{" "}
              <a href="mailto:support@careera.co" className="text-white underline hover:text-zinc-300">
                support@careera.co
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY
              KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES
              OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
              CAREERA DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE,
              OR SECURE.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CAREERA AND ITS OFFICERS, DIRECTORS,
              EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF
              THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL
              THEORY. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE
              SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Careera and its affiliates from any
              claims, damages, losses, or expenses (including reasonable attorneys' fees)
              arising from your use of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of
              the State of Delaware, United States, without regard to its conflict of law
              provisions. Any disputes arising under these Terms shall be resolved in the
              courts located in Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">12. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at
              any time, with or without cause, and with or without notice. Upon termination,
              your right to use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-lg sm:text-xl font-semibold text-white mb-3">13. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:support@careera.co" className="text-white underline hover:text-zinc-300">
                support@careera.co
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-zinc-800 text-center text-xs text-zinc-500">
          &copy; 2026 Careera. All rights reserved.
        </div>
      </div>
    </div>
  );
}
